### Loading the Source Links

In [1]:
import pandas as pd
df= pd.read_excel(r"C:\z_Learn\miraj_pandas\Ml_Project\Data\Mainn_OnlineKhabar_Posts.xlsx")
df.head()

,Posts,URL
0,Three ministers get additional portfolios,{'url': 'https://english.onlinekhabar.com/thre...
1,Legal ways paved to provide citizenship in mot...,{'url': 'https://english.onlinekhabar.com/lega...
2,"Upcoming HoR election to see deployment of 80,...",{'url': 'https://english.onlinekhabar.com/upco...
3,New regulation incorporated into the Election ...,{'url': 'https://english.onlinekhabar.com/new-...
4,Energy Minister Ghising resigns,{'url': 'https://english.onlinekhabar.com/ener...

### Preprocessing the data

In [2]:
import ast
df["URL"] = df["URL"].apply(ast.literal_eval)
df["Category"] = df["URL"].apply(lambda x: x["category"])
df["Link"] = df["URL"].apply(lambda x: x["url"])

In [3]:
df.head()

,Posts,URL,Category,Link
0,Three ministers get additional portfolios,{'url': 'https://english.onlinekhabar.com/thre...,Politics,https://english.onlinekhabar.com/three-ministe...
1,Legal ways paved to provide citizenship in mot...,{'url': 'https://english.onlinekhabar.com/lega...,Politics,https://english.onlinekhabar.com/legal-ways-pa...
2,"Upcoming HoR election to see deployment of 80,...",{'url': 'https://english.onlinekhabar.com/upco...,Politics,https://english.onlinekhabar.com/upcoming-hor-...
3,New regulation incorporated into the Election ...,{'url': 'https://english.onlinekhabar.com/new-...,Politics,https://english.onlinekhabar.com/new-regulatio...
4,Energy Minister Ghising resigns,{'url': 'https://english.onlinekhabar.com/ener...,Politics,https://english.onlinekhabar.com/energy-minist...

### Disable SSL Checks

In [4]:
import requests
import urllib3

def disable_ssl_verification():
    """Disable SSL certificate verification globally for requests."""
    urllib3.disable_warnings(urllib3.exceptions.InsecureRequestWarning)

    original_request = requests.Session.request

    def request_without_ssl(self, *args, **kwargs):
        kwargs["verify"] = False
        return original_request(self, *args, **kwargs)

    requests.Session.request = request_without_ssl

### Retriving the One Page Content

In [5]:
first_link = df['Link'].at[0]
first_link

'https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html'

In [6]:
disable_ssl_verification()
import requests
response = requests.get(first_link)
response.text

'<!doctype html>\n<html lang="en-GB" prefix="og: https://ogp.me/ns#">\n    <head>\n        <meta charset="UTF-8">\n        <meta name="viewport" content="width=device-width, initial-scale=1">\n        <link rel="profile" href="https://gmpg.org/xfn/11">\n\n        \n<!-- Search Engine Optimization by Rank Math - https://rankmath.com/ -->\n<title>Three ministers get additional portfolios - OnlineKhabar English News</title>\n<meta name="description" content="President Ramchandra Paudel has assigned additional portfolios to three ministers. The responsibility of three ministries was given to other ministers after"/>\n<meta name="robots" content="follow, index, max-snippet:-1, max-video-preview:-1, max-image-preview:large"/>\n<link rel="canonical" href="https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html" />\n<meta property="og:locale" content="en_GB" />\n<meta property="og:type" content="article" />\n<meta property="og:title" content="Three ministers get additional portfolios - OnlineKhabar English News" />\n<meta property="og:description" content="President Ramchandra Paudel has assigned additional portfolios to three ministers. The responsibility of three ministries was given to other ministers after" />\n<meta property="og:url" content="https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html" />\n<meta property="og:site_name" content="OnlineKhabar English News" />\n<meta property="article:publisher" content="https://www.facebook.com/pages/OnlineKhabar/108349739223556" />\n<meta property="article:tag" content="ministers" />\n<meta property="article:section" content="Politics" />\n<meta property="og:updated_time" content="2026-01-09T14:51:45+05:45" />\n<meta property="og:image" content="https://english.onlinekhabar.com/wp-content/uploads/2017/02/Pm-office-5.jpg" />\n<meta property="og:image:secure_url" content="https://english.onlinekhabar.com/wp-content/uploads/2017/02/Pm-office-5.jpg" />\n<meta property="og:image:width" content="810" />\n<meta property="og:image:height" content="446" />\n<meta property="og:image:alt" content="How long will government formation take after the election" />\n<meta property="og:image:type" content="image/jpeg" />\n<meta property="article:published_time" content="2026-01-09T14:00:16+05:45" />\n<meta property="article:modified_time" content="2026-01-09T14:51:45+05:45" />\n<meta name="twitter:card" content="summary_large_image" />\n<meta name="twitter:title" content="Three ministers get additional portfolios - OnlineKhabar English News" />\n<meta name="twitter:description" content="President Ramchandra Paudel has assigned additional portfolios to three ministers. The responsibility of three ministries was given to other ministers after" />\n<meta name="twitter:site" content="@online_khabar" />\n<meta name="twitter:creator" content="@online_khabar" />\n<meta name="twitter:image" content="https://english.onlinekhabar.com/wp-content/uploads/2017/02/Pm-office-5.jpg" />\n<meta name="twitter:label1" content="Written by" />\n<meta name="twitter:data1" content="Sangita Shrestha" />\n<meta name="twitter:label2" content="Time to read" />\n<meta name="twitter:data2" content="Less than a minute" />\n<script type="application/ld+json" class="rank-math-schema">{"@context":"https://schema.org","@graph":[{"@type":["Person","Organization"],"@id":"https://english.onlinekhabar.com/#person","name":"admin","sameAs":["https://www.facebook.com/pages/OnlineKhabar/108349739223556","https://twitter.com/online_khabar"],"logo":{"@type":"ImageObject","@id":"https://english.onlinekhabar.com/#logo","url":"http://english.onlinekhabar.com/wp-content/uploads/2020/09/ok-english-logo-onlinekhabar.png","contentUrl":"http://english.onlinekhabar.com/wp-content/uploads/2020/09/ok-english-logo-onlinekhabar.png","caption":"admin","inLanguage":"en-GB","width":"459","height":"74"},"image":{"@type":"ImageObject","@id":"https://english.onlinekhabar.com/#logo","url":"http://english.onlinekhabar.com/wp-content/uploads/2020/09/ok-english-logo-onlinekhabar.png","contentUrl":"http://english.onlinekhabar.com/wp-content/uploads/2020/09/ok-english-logo-onlinekhabar.png","caption":"admin","inLanguage":"en-GB","width":"459","height":"74"}},{"@type":"WebSite","@id":"https://english.onlinekhabar.com/#website","url":"https://english.onlinekhabar.com","name":"admin","publisher":{"@id":"https://english.onlinekhabar.com/#person"},"inLanguage":"en-GB"},{"@type":"ImageObject","@id":"https://english.onlinekhabar.com/wp-content/uploads/2017/02/Pm-office-5.jpg","url":"https://english.onlinekhabar.com/wp-content/uploads/2017/02/Pm-office-5.jpg","width":"810","height":"446","caption":"How long will government formation take after the election","inLanguage":"en-GB"},{"@type":"BreadcrumbList","@id":"https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html#breadcrumb","itemListElement":[{"@type":"ListItem","position":"1","item":{"@id":"https://english.onlinekhabar.com","name":"Home"}},{"@type":"ListItem","position":"2","item":{"@id":"https://english.onlinekhabar.com/category/political","name":"Politics"}},{"@type":"ListItem","position":"3","item":{"@id":"https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html","name":"Three ministers get additional portfolios"}}]},{"@type":"WebPage","@id":"https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html#webpage","url":"https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html","name":"Three ministers get additional portfolios - OnlineKhabar English News","datePublished":"2026-01-09T14:00:16+05:45","dateModified":"2026-01-09T14:51:45+05:45","isPartOf":{"@id":"https://english.onlinekhabar.com/#website"},"primaryImageOfPage":{"@id":"https://english.onlinekhabar.com/wp-content/uploads/2017/02/Pm-office-5.jpg"},"inLanguage":"en-GB","breadcrumb":{"@id":"https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html#breadcrumb"}},{"@type":"Person","@id":"https://english.onlinekhabar.com/author/sangita","name":"Sangita Shrestha","url":"https://english.onlinekhabar.com/author/sangita","image":{"@type":"ImageObject","@id":"https://secure.gravatar.com/avatar/ea6bfb1e962da1375acc8256b985218a15e7e0f963b130909119b883bac9e3c0?s=96&amp;d=mm&amp;r=g","url":"https://secure.gravatar.com/avatar/ea6bfb1e962da1375acc8256b985218a15e7e0f963b130909119b883bac9e3c0?s=96&amp;d=mm&amp;r=g","caption":"Sangita Shrestha","inLanguage":"en-GB"}},{"@type":"NewsArticle","headline":"Three ministers get additional portfolios - OnlineKhabar English News","keywords":"ministers","datePublished":"2026-01-09T14:00:16+05:45","dateModified":"2026-01-09T14:51:45+05:45","articleSection":"Politics","author":{"@id":"https://english.onlinekhabar.com/author/sangita","name":"Sangita Shrestha"},"publisher":{"@id":"https://english.onlinekhabar.com/#person"},"description":"President Ramchandra Paudel has assigned additional portfolios to three ministers. The responsibility of three ministries was given to other ministers after","name":"Three ministers get additional portfolios - OnlineKhabar English News","@id":"https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html#richSnippet","isPartOf":{"@id":"https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html#webpage"},"image":{"@id":"https://english.onlinekhabar.com/wp-content/uploads/2017/02/Pm-office-5.jpg"},"inLanguage":"en-GB","mainEntityOfPage":{"@id":"https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html#webpage"}}]}</script>\n<!-- /Rank Math WordPress SEO plugin -->\n\n<link rel=\'dns-prefetch\' href=\'//challenges.cloudflare.com\' />\n<link rel=\'dns-prefetch\' href=\'//unpkg.com\' />\n<link rel="alternate" type="application/rss+xml" title="OnlineKhabar English News &raquo; Feed" href="https://english.onlinekhabar.com/feed" />\n<link rel="alternate" type="application/rss+xml" title="OnlineKhabar English News &raquo; Comments Feed" href="https://english.onlinekhabar.com/comments/feed" />\n<link rel="alternate" title="oEmbed (JSON)" type="application/json+oembed" href="https://english.onlinekhabar.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fenglish.onlinekhabar.com%2Fthree-ministers-get-additional-portfolios.html" />\n<link rel="alternate" title="oEmbed (XML)" type="text/xml+oembed" href="https://english.onlinekhabar.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fenglish.onlinekhabar.com%2Fthree-ministers-get-additional-portfolios.html&#038;format=xml" />\n<style id="wp-img-auto-sizes-contain-inline-css">\nimg:is([sizes=auto i],[sizes^="auto," i]){contain-intrinsic-size:3000px 1500px}\n/*# sourceURL=wp-img-auto-sizes-contain-inline-css */\n</style>\n<style id="wp-emoji-styles-inline-css">\n\n\timg.wp-smiley, img.emoji {\n\t\tdisplay: inline !important;\n\t\tborder: none !important;\n\t\tbox-shadow: none !important;\n\t\theight: 1em !important;\n\t\twidth: 1em !important;\n\t\tmargin: 0 0.07em !important;\n\t\tvertical-align: -0.1em !important;\n\t\tbackground: none !important;\n\t\tpadding: 0 !important;\n\t}\n/*# sourceURL=wp-emoji-styles-inline-css */\n</style>\n<style id="wp-block-library-inline-css">\n:root{--wp-block-synced-color:#7a00df;--wp-block-synced-color--rgb:122,0,223;--wp-bound-block-color:var(--wp-block-synced-color);--wp-editor-canvas-background:#ddd;--wp-admin-theme-color:#007cba;--wp-admin-theme-color--rgb:0,124,186;--wp-admin-theme-color-darker-10:#006ba1;--wp-admin-theme-color-darker-10--rgb:0,107,160.5;--wp-admin-theme-color-darker-20:#005a87;--wp-admin-theme-color-darker-20--rgb:0,90,135;--wp-admin-border-width-focus:2px}@media (min-resolution:192dpi){:root{--wp-admin-border-width-focus:1.5px}}.wp-element-button{cursor:pointer}:root .has-very-light-gray-background-color{background-color:#eee}:root .has-very-dark-gray-background-color{background-color:#313131}:root .has-very-light-gray-color{color:#eee}:root .has-very-dark-gray-color{color:#313131}:root .has-vivid-green-cyan-to-vivid-cyan-blue-gradient-background{background:linear-gradient(135deg,#00d084,#0693e3)}:root .has-purple-crush-gradient-background{background:linear-gradient(135deg,#34e2e4,#4721fb 50%,#ab1dfe)}:root .has-hazy-dawn-gradient-background{background:linear-gradient(135deg,#faaca8,#dad0ec)}:root .has-subdued-olive-gradient-background{background:linear-gradient(135deg,#fafae1,#67a671)}:root .has-atomic-cream-gradient-background{background:linear-gradient(135deg,#fdd79a,#004a59)}:root .has-nightshade-gradient-background{background:linear-gradient(135deg,#330968,#31cdcf)}:root .has-midnight-gradient-background{background:linear-gradient(135deg,#020381,#2874fc)}:root{--wp--preset--font-size--normal:16px;--wp--preset--font-size--huge:42px}.has-regular-font-size{font-size:1em}.has-larger-font-size{font-size:2.625em}.has-normal-font-size{font-size:var(--wp--preset--font-size--normal)}.has-huge-font-size{font-size:var(--wp--preset--font-size--huge)}:root .has-text-align-center{text-align:center}:root .has-text-align-left{text-align:left}:root .has-text-align-right{text-align:right}.has-fit-text{white-space:nowrap!important}#end-resizable-editor-section{display:none}.aligncenter{clear:both}.items-justified-left{justify-content:flex-start}.items-justified-center{justify-content:center}.items-justified-right{justify-content:flex-end}.items-justified-space-between{justify-content:space-between}.screen-reader-text{word-wrap:normal!important;border:0;clip-path:inset(50%);height:1px;margin:-1px;overflow:hidden;padding:0;position:absolute;width:1px}.screen-reader-text:focus{background-color:#ddd;clip-path:none;color:#444;display:block;font-size:1em;height:auto;left:5px;line-height:normal;padding:15px 23px 14px;text-decoration:none;top:5px;width:auto;z-index:100000}html :where(.has-border-color){border-style:solid}html :where([style*=border-color]){border-style:solid}html :where([style*=border-top-color]){border-top-style:solid}html :where([style*=border-right-color]){border-right-style:solid}html :where([style*=border-bottom-color]){border-bottom-style:solid}html :where([style*=border-left-color]){border-left-style:solid}html :where([style*=border-width]){border-style:solid}html :where([style*=border-top-width]){border-top-style:solid}html :where([style*=border-right-width]){border-right-style:solid}html :where([style*=border-bottom-width]){border-bottom-style:solid}html :where([style*=border-left-width]){border-left-style:solid}html :where(img[class*=wp-image-]){height:auto;max-width:100%}:where(figure){margin:0 0 1em}html :where(.is-position-sticky){--wp-admin--admin-bar--position-offset:var(--wp-admin--admin-bar--height,0px)}@media screen and (max-width:600px){html :where(.is-position-sticky){--wp-admin--admin-bar--position-offset:0px}}\n\n/*# sourceURL=/wp-includes/css/dist/block-library/common.min.css */\n</style>\n<style id="wp-block-image-inline-css">\n.wp-block-image>a,.wp-block-image>figure>a{display:inline-block}.wp-block-image img{box-sizing:border-box;height:auto;max-width:100%;vertical-align:bottom}@media not (prefers-reduced-motion){.wp-block-image img.hide{visibility:hidden}.wp-block-image img.show{animation:show-content-image .4s}}.wp-block-image[style*=border-radius] img,.wp-block-image[style*=border-radius]>a{border-radius:inherit}.wp-block-image.has-custom-border img{box-sizing:border-box}.wp-block-image.aligncenter{text-align:center}.wp-block-image.alignfull>a,.wp-block-image.alignwide>a{width:100%}.wp-block-image.alignfull img,.wp-block-image.alignwide img{height:auto;width:100%}.wp-block-image .aligncenter,.wp-block-image .alignleft,.wp-block-image .alignright,.wp-block-image.aligncenter,.wp-block-image.alignleft,.wp-block-image.alignright{display:table}.wp-block-image .aligncenter>figcaption,.wp-block-image .alignleft>figcaption,.wp-block-image .alignright>figcaption,.wp-block-image.aligncenter>figcaption,.wp-block-image.alignleft>figcaption,.wp-block-image.alignright>figcaption{caption-side:bottom;display:table-caption}.wp-block-image .alignleft{float:left;margin:.5em 1em .5em 0}.wp-block-image .alignright{float:right;margin:.5em 0 .5em 1em}.wp-block-image .aligncenter{margin-left:auto;margin-right:auto}.wp-block-image :where(figcaption){margin-bottom:1em;margin-top:.5em}.wp-block-image.is-style-circle-mask img{border-radius:9999px}@supports ((-webkit-mask-image:none) or (mask-image:none)) or (-webkit-mask-image:none){.wp-block-image.is-style-circle-mask img{border-radius:0;-webkit-mask-image:url(\'data:image/svg+xml;utf8,<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="50"/></svg>\');mask-image:url(\'data:image/svg+xml;utf8,<svg viewBox="0 0 100 100" xmlns="http://www.w3.org/2000/svg"><circle cx="50" cy="50" r="50"/></svg>\');mask-mode:alpha;-webkit-mask-position:center;mask-position:center;-webkit-mask-repeat:no-repeat;mask-repeat:no-repeat;-webkit-mask-size:contain;mask-size:contain}}:root :where(.wp-block-image.is-style-rounded img,.wp-block-image .is-style-rounded img){border-radius:9999px}.wp-block-image figure{margin:0}.wp-lightbox-container{display:flex;flex-direction:column;position:relative}.wp-lightbox-container img{cursor:zoom-in}.wp-lightbox-container img:hover+button{opacity:1}.wp-lightbox-container button{align-items:center;backdrop-filter:blur(16px) saturate(180%);background-color:#5a5a5a40;border:none;border-radius:4px;cursor:zoom-in;display:flex;height:20px;justify-content:center;opacity:0;padding:0;position:absolute;right:16px;text-align:center;top:16px;width:20px;z-index:100}@media not (prefers-reduced-motion){.wp-lightbox-container button{transition:opacity .2s ease}}.wp-lightbox-container button:focus-visible{outline:3px auto #5a5a5a40;outline:3px auto -webkit-focus-ring-color;outline-offset:3px}.wp-lightbox-container button:hover{cursor:pointer;opacity:1}.wp-lightbox-container button:focus{opacity:1}.wp-lightbox-container button:focus,.wp-lightbox-container button:hover,.wp-lightbox-container button:not(:hover):not(:active):not(.has-background){background-color:#5a5a5a40;border:none}.wp-lightbox-overlay{box-sizing:border-box;cursor:zoom-out;height:100vh;left:0;overflow:hidden;position:fixed;top:0;visibility:hidden;width:100%;z-index:100000}.wp-lightbox-overlay .wp-lightbox-close-button{align-items:center;cursor:pointer;display:flex;font-family:inherit;gap:8px;justify-content:center;line-height:1;min-height:40px;min-width:40px;padding:0 4px;position:absolute;right:calc(env(safe-area-inset-right) + 16px);top:calc(env(safe-area-inset-top) + 16px);z-index:5000000}.wp-lightbox-overlay .wp-lightbox-close-button:focus,.wp-lightbox-overlay .wp-lightbox-close-button:hover,.wp-lightbox-overlay .wp-lightbox-close-button:not(:hover):not(:active):not(.has-background){background:none;border:none}.wp-lightbox-overlay .wp-lightbox-close-button:has(.wp-lightbox-close-text:not([hidden])) .wp-lightbox-close-icon svg{height:1em;width:1em}.wp-lightbox-overlay .wp-lightbox-close-icon svg{display:block}.wp-lightbox-overlay .wp-lightbox-navigation-button-next,.wp-lightbox-overlay .wp-lightbox-navigation-button-prev{align-items:center;bottom:16px;cursor:pointer;display:flex;font-family:inherit;gap:4px;justify-content:center;line-height:1;min-height:40px;min-width:40px;padding:0 8px;position:absolute;z-index:2000002}.wp-lightbox-overlay .wp-lightbox-navigation-button-next[hidden],.wp-lightbox-overlay .wp-lightbox-navigation-button-prev[hidden]{display:none}@media (min-width:960px){.wp-lightbox-overlay .wp-lightbox-navigation-button-next,.wp-lightbox-overlay .wp-lightbox-navigation-button-prev{bottom:50%;transform:translateY(-50%)}}.wp-lightbox-overlay .wp-lightbox-navigation-button-next:focus,.wp-lightbox-overlay .wp-lightbox-navigation-button-next:hover,.wp-lightbox-overlay .wp-lightbox-navigation-button-next:not(:hover):not(:active):not(.has-background),.wp-lightbox-overlay .wp-lightbox-navigation-button-prev:focus,.wp-lightbox-overlay .wp-lightbox-navigation-button-prev:hover,.wp-lightbox-overlay .wp-lightbox-navigation-button-prev:not(:hover):not(:active):not(.has-background){background:none;border:none;padding:0 8px}.wp-lightbox-overlay .wp-lightbox-navigation-button-next:has(.wp-lightbox-navigation-text:not([hidden])) .wp-lightbox-navigation-icon svg,.wp-lightbox-overlay .wp-lightbox-navigation-button-prev:has(.wp-lightbox-navigation-text:not([hidden])) .wp-lightbox-navigation-icon svg{display:block;height:1.5em;width:1.5em}.wp-lightbox-overlay .wp-lightbox-navigation-button-prev{left:calc(env(safe-area-inset-left) + 16px)}.wp-lightbox-overlay .wp-lightbox-navigation-button-next{right:calc(env(safe-area-inset-right) + 16px)}.wp-lightbox-overlay .wp-lightbox-navigation-icon svg{vertical-align:middle}.wp-lightbox-overlay .lightbox-image-container{height:var(--wp--lightbox-container-height);left:50%;overflow:hidden;position:absolute;top:50%;transform:translate(-50%,-50%);transform-origin:top left;width:var(--wp--lightbox-container-width);z-index:2000001}.wp-lightbox-overlay .wp-block-image{align-items:center;box-sizing:border-box;display:flex;height:100%;justify-content:center;margin:0;position:relative;transform-origin:0 0;width:100%;z-index:3000000}.wp-lightbox-overlay .wp-block-image img{height:var(--wp--lightbox-image-height);min-height:var(--wp--lightbox-image-height);min-width:var(--wp--lightbox-image-width);width:var(--wp--lightbox-image-width)}.wp-lightbox-overlay .wp-block-image figcaption{display:none}.wp-lightbox-overlay button{background:none;border:none}.wp-lightbox-overlay .scrim{background-color:#fff;height:100%;opacity:.9;position:absolute;width:100%;z-index:2000000}.wp-lightbox-overlay.active{visibility:visible}@media not (prefers-reduced-motion){.wp-lightbox-overlay.active{animation:turn-on-visibility .25s both}.wp-lightbox-overlay.active img{animation:turn-on-visibility .35s both}.wp-lightbox-overlay.show-closing-animation:not(.active){animation:turn-off-visibility .35s both}.wp-lightbox-overlay.show-closing-animation:not(.active)

### Converting the HTML to Soup

In [7]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(response.text, 'html.parser')
print(soup.prettify())  # Print the formatted HTML content

<!DOCTYPE html>
<html lang="en-GB" prefix="og: https://ogp.me/ns#">
 <head>
  <meta charset="utf-8"/>
  <meta content="width=device-width, initial-scale=1" name="viewport"/>
  <link href="https://gmpg.org/xfn/11" rel="profile"/>
  <!-- Search Engine Optimization by Rank Math - https://rankmath.com/ -->
  <title>
   Three ministers get additional portfolios - OnlineKhabar English News
  </title>
  <meta content="President Ramchandra Paudel has assigned additional portfolios to three ministers. The responsibility of three ministries was given to other ministers after" name="description"/>
  <meta content="follow, index, max-snippet:-1, max-video-preview:-1, max-image-preview:large" name="robots"/>
  <link href="https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html" rel="canonical"/>
  <meta content="en_GB" property="og:locale"/>
  <meta content="article" property="og:type"/>
  <meta content="Three ministers get additional portfolios - OnlineKhabar English News" property="og:title"/>
  <meta content="President Ramchandra Paudel has assigned additional portfolios to three ministers. The responsibility of three ministries was given to other ministers after" property="og:description"/>
  <meta content="https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html" property="og:url"/>
  <meta content="OnlineKhabar English News" property="og:site_name"/>
  <meta content="https://www.facebook.com/pages/OnlineKhabar/108349739223556" property="article:publisher"/>
  <meta content="ministers" property="article:tag"/>
  <meta content="Politics" property="article:section"/>
  <meta content="2026-01-09T14:51:45+05:45" property="og:updated_time"/>
  <meta content="https://english.onlinekhabar.com/wp-content/uploads/2017/02/Pm-office-5.jpg" property="og:image"/>
  <meta content="https://english.onlinekhabar.com/wp-content/uploads/2017/02/Pm-office-5.jpg" property="og:image:secure_url"/>
  <meta content="810" property="og:image:width"/>
  <meta content="446" property="og:image:height"/>
  <meta content="How long will government formation take after the election" property="og:image:alt"/>
  <meta content="image/jpeg" property="og:image:type"/>
  <meta content="2026-01-09T14:00:16+05:45" property="article:published_time"/>
  <meta content="2026-01-09T14:51:45+05:45" property="article:modified_time"/>
  <meta content="summary_large_image" name="twitter:card"/>
  <meta content="Three ministers get additional portfolios - OnlineKhabar English News" name="twitter:title"/>
  <meta content="President Ramchandra Paudel has assigned additional portfolios to three ministers. The responsibility of three ministries was given to other ministers after" name="twitter:description"/>
  <meta content="@online_khabar" name="twitter:site"/>
  <meta content="@online_khabar" name="twitter:creator"/>
  <meta content="https://english.onlinekhabar.com/wp-content/uploads/2017/02/Pm-office-5.jpg" name="twitter:image"/>
  <meta content="Written by" name="twitter:label1"/>
  <meta content="Sangita Shrestha" name="twitter:data1"/>
  <meta content="Time to read" name="twitter:label2"/>
  <meta content="Less than a minute" name="twitter:data2"/>
  <script class="rank-math-schema" type="application/ld+json">
   {"@context":"https://schema.org","@graph":[{"@type":["Person","Organization"],"@id":"https://english.onlinekhabar.com/#person","name":"admin","sameAs":["https://www.facebook.com/pages/OnlineKhabar/108349739223556","https://twitter.com/online_khabar"],"logo":{"@type":"ImageObject","@id":"https://english.onlinekhabar.com/#logo","url":"http://english.onlinekhabar.com/wp-content/uploads/2020/09/ok-english-logo-onlinekhabar.png","contentUrl":"http://english.onlinekhabar.com/wp-content/uploads/2020/09/ok-english-logo-onlinekhabar.png","caption":"admin","inLanguage":"en-GB","width":"459","height":"74"},"image":{"@type":"ImageObject","@id":"https://english.onlinekhabar.com/#logo","url":"http://english.onlinekhabar.com/wp-content/uploads/2020/09/ok-english-logo-onlinekhabar.png","contentUrl":"http://english.onlinekhabar.com/wp-content/uploads/2020/09/ok-english-logo-onlinekhabar.png","caption":"admin","inLanguage":"en-GB","width":"459","height":"74"}},{"@type":"WebSite","@id":"https://english.onlinekhabar.com/#website","url":"https://english.onlinekhabar.com","name":"admin","publisher":{"@id":"https://english.onlinekhabar.com/#person"},"inLanguage":"en-GB"},{"@type":"ImageObject","@id":"https://english.onlinekhabar.com/wp-content/uploads/2017/02/Pm-office-5.jpg","url":"https://english.onlinekhabar.com/wp-content/uploads/2017/02/Pm-office-5.jpg","width":"810","height":"446","caption":"How long will government formation take after the election","inLanguage":"en-GB"},{"@type":"BreadcrumbList","@id":"https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html#breadcrumb","itemListElement":[{"@type":"ListItem","position":"1","item":{"@id":"https://english.onlinekhabar.com","name":"Home"}},{"@type":"ListItem","position":"2","item":{"@id":"https://english.onlinekhabar.com/category/political","name":"Politics"}},{"@type":"ListItem","position":"3","item":{"@id":"https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html","name":"Three ministers get additional portfolios"}}]},{"@type":"WebPage","@id":"https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html#webpage","url":"https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html","name":"Three ministers get additional portfolios - OnlineKhabar English News","datePublished":"2026-01-09T14:00:16+05:45","dateModified":"2026-01-09T14:51:45+05:45","isPartOf":{"@id":"https://english.onlinekhabar.com/#website"},"primaryImageOfPage":{"@id":"https://english.onlinekhabar.com/wp-content/uploads/2017/02/Pm-office-5.jpg"},"inLanguage":"en-GB","breadcrumb":{"@id":"https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html#breadcrumb"}},{"@type":"Person","@id":"https://english.onlinekhabar.com/author/sangita","name":"Sangita Shrestha","url":"https://english.onlinekhabar.com/author/sangita","image":{"@type":"ImageObject","@id":"https://secure.gravatar.com/avatar/ea6bfb1e962da1375acc8256b985218a15e7e0f963b130909119b883bac9e3c0?s=96&amp;d=mm&amp;r=g","url":"https://secure.gravatar.com/avatar/ea6bfb1e962da1375acc8256b985218a15e7e0f963b130909119b883bac9e3c0?s=96&amp;d=mm&amp;r=g","caption":"Sangita Shrestha","inLanguage":"en-GB"}},{"@type":"NewsArticle","headline":"Three ministers get additional portfolios - OnlineKhabar English News","keywords":"ministers","datePublished":"2026-01-09T14:00:16+05:45","dateModified":"2026-01-09T14:51:45+05:45","articleSection":"Politics","author":{"@id":"https://english.onlinekhabar.com/author/sangita","name":"Sangita Shrestha"},"publisher":{"@id":"https://english.onlinekhabar.com/#person"},"description":"President Ramchandra Paudel has assigned additional portfolios to three ministers. The responsibility of three ministries was given to other ministers after","name":"Three ministers get additional portfolios - OnlineKhabar English News","@id":"https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html#richSnippet","isPartOf":{"@id":"https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html#webpage"},"image":{"@id":"https://english.onlinekhabar.com/wp-content/uploads/2017/02/Pm-office-5.jpg"},"inLanguage":"en-GB","mainEntityOfPage":{"@id":"https://english.onlinekhabar.com/three-ministers-get-additional-portfolios.html#webpage"}}]}
  </script>
  <!-- /Rank Math WordPress SEO plugin -->
  <link href="//challenges.cloudflare.com" rel="dns-prefetch"/>
  <link href="//unpkg.com" rel="dns-prefetch"/>
  <link href="https://english.onlinekhabar.com/feed" rel="alternate" title="OnlineKhabar English News » Feed" type="application/rss+xml"/>
  <link href="https://english.onlinekhabar.com/comments/feed" rel="alternate" title="OnlineKhabar English News » Comments Feed" type="application/rss+xml"/>
  <link href="https://english.onlinekhabar.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fenglish.onlinekhabar.com%2Fthree-ministers-get-additional-portfolios.html" rel="alternate" title="oEmbed (JSON)" type="application/json+oembed"/>
  <link href="https://english.onlinekhabar.com/wp-json/oembed/1.0/embed?url=https%3A%2F%2Fenglish.onlinekhabar.com%2Fthree-ministers-get-additional-portfolios.html&amp;format=xml" rel="alternate" title="oEmbed (XML)" type="text/xml+oembed"/>
  <style id="wp-img-auto-sizes-contain-inline-css">
   img:is([sizes=auto i],[sizes^="auto," i]){contain-intrinsic-size:3000px 1500px}
/*# sourceURL=wp-img-auto-sizes-contain-inline-css */
  </style>
  <style id="wp-emoji-styles-inline-css">
   img.wp-smiley, img.emoji {
		display: inline !important;
		border: none !important;
		box-shadow: none !important;
		height: 1em !important;
		width: 1em !important;
		margin: 0 0.07em !important;
		vertical-align: -0.1em !important;
		background: none !important;
		padding: 0 !important;
	}
/*# sourceURL=wp-emoji-styles-inline-css */
  </style>
  <style id="wp-block-library-inline-css">
   :root{--wp-block-synced-color:#7a00df;--wp-block-synced-color--rgb:122,0,223;--wp-bound-block-color:var(--wp-block-synced-color);--wp-editor-canvas-background:#ddd;--wp-admin-theme-color:#007cba;--wp-admin-theme-color--rgb:0,124,186;--wp-admin-theme-color-darker-10:#006ba1;--wp-admin-theme-color-darker-10--rgb:0,107,160.5;--wp-admin-theme-color-darker-20:#005a87;--wp-admin-theme-color-darker-20--rgb:0,90,135;--wp-admin-border-width-focus:2px}@media (min-resolution:192dpi){:root{--wp-admin-border-width-focus:1.5px}}.wp-element-button{cursor:pointer}:root .has-very-light-gray-background-color{background-color:#eee}:root .has-very-dark-gray-background-color{background-color:#313131}:root .has-very-light-gray-color{color:#eee}:root .has-very-dark-gray-color{color:#313131}:root .has-vivid-green-cyan-to-vivid-cyan-blue-gradient-background{background:linear-gradient(135deg,#00d084,#0693e3)}:root .has-purple-crush-gradient-background{background:linear-gradient(135deg,#34e2e4,#4721fb 50%,#ab1dfe)}:root .has-hazy-dawn-gradient-background{background:linear-gradient(135deg,#faaca8,#dad0ec)}:root .has-subdued-olive-gradient-background{background:linear-gradient(135deg,#fafae1,#67a671)}:root .has-atomic-cream-gradient-background{background:linear-gradient(135deg,#fdd79a,#004a59)}:root .has-nightshade-gradient-background{background:linear-gradient(135deg,#330968,#31cdcf)}:root .has-midnight-gradient-background{background:linear-gradient(135deg,#020381,#2874fc)}:root{--wp--preset--font-size--normal:16px;--wp--preset--font-size--huge:42px}.has-regular-font-size{font-size:1em}.has-larger-font-size{font-size:2.625em}.has-normal-font-size{font-size:var(--wp--preset--font-size--normal)}.has-huge-font-size{font-size:var(--wp--preset--font-size--huge)}:root .has-text-align-center{text-align:center}:root .has-text-align-left{text-align:left}:root .has-text-align-right{text-align:right}.has-fit-text{white-space:nowrap!important}#end-resizable-editor-section{display:none}.aligncenter{clear:both}.items-justified-left{justify-content:flex-start}.items-justified-center{justify-content:center}.items-justified-right{justify-content:flex-end}.items-justified-space-between{justify-content:space-between}.screen-reader-text{word-wrap:normal!important;border:0;clip-path:inset(50%);height:1px;margin:-1px;overflow:hidden;padding:0;position:absolute;width:1px}.screen-reader-text:focus{background-color:#ddd;clip-path:none;color:#444;display:block;font-size:1em;height:auto;left:5px;line-height:normal;padding:15px 23px 14px;text-decoration:none;top:5px;width:auto;z-index:100000}html :where(.has-border-color){border-style:solid}html :where([style*=border-color]){border-style:solid}html :where([style*=border-top-color]){border-top-style:solid}html :where([style*=border-right-color]){border-right-style:solid}html :where([style*=border-bottom-color]){border-bottom-style:solid}html :where([style*=border-left-color]){border-left-style:solid}html :where([style*=border-width]){border-style:solid}html :where([style*=border-top-width]){border-top-style:solid}html :where([style*=border-right-width]){border-right-style:solid}html :where([style*=border-bottom-width]){border-bottom-style:solid}html :where([style*=border-left-width]){border-left-style:solid}html :where(img[class*=wp-image-]){height:auto;max-width:100%}:where(figure){margin:0 0 1em}html :where(.is-position-sticky){--wp-admin--admin-bar--position-offset:var(--wp-admin--admin-bar--height,0px)}@media screen and (max-width:600px){html :where(.is-position-sticky){--wp-admin--admin-bar--position-offset:0px}}

/*# sourceURL=/wp-includes/css/dist/block-library/common.min.css */
  </style>
  <style id="wp-block-image-inline-css">

### Retrving all the Text Content from Post Page

In [8]:
text_section = soup.find('div', class_='post-content-wrap')
text_section

<div class="post-content-wrap">
<figure class="wp-block-image size-full"><img alt="" class="wp-image-395611" decoding="async" fetchpriority="high" height="446" sizes="(max-width: 810px) 100vw, 810px" src="https://english.onlinekhabar.com/wp-content/uploads/2017/02/Pm-office-5.jpg" srcset="https://english.onlinekhabar.com/wp-content/uploads/2017/02/Pm-office-5.jpg 810w, https://english.onlinekhabar.com/wp-content/uploads/2017/02/Pm-office-5-300x165.jpg 300w, https://english.onlinekhabar.com/wp-content/uploads/2017/02/Pm-office-5-768x423.jpg 768w" width="810"/><figcaption class="wp-element-caption">File image: Office of the Prime Minister and Council of Ministers</figcaption></figure>
<p class="wp-block-paragraph">Kathmandu, January 9</p>
<p class="wp-block-paragraph">President Ramchandra Paudel has assigned additional portfolios to three ministers. The responsibility of three ministries was given to other ministers after Kul Man Ghising, who had been taking charge of the Ministry of Energy, Water Resources and Irrigation, the Ministry of Physical Infrastructures and Transport, and the Ministry of Urban Development, resigned from the post on Wednesday.</p>
<p class="wp-block-paragraph">At the recommendation of Prime Minister Sushila Karki, President Paudel assigned Minister for Industry, Commerce and Supply, Anil Kumar Sinha, to look after the portfolio of the Ministry of Energy, Water Resources and Irrigation.</p>
<p class="wp-block-paragraph">Similarly, Minister for Forest and Environment, Madhav Prasad Chaulagain, will look after the portfolio of the Ministry of Physical Infrastructures and Transport, while Minister for Land Management, Cooperative and Poverty Alleviation, Kumar Ingnam, the portfolio of the Urban Development Minister, as well, reads a press release issued by Spokesperson at the Office of the President, Ritesh Kumar Shakya.</p>
</div>

In [9]:
text_section.find_all('p')

[<p class="wp-block-paragraph">Kathmandu, January 9</p>,
 <p class="wp-block-paragraph">President Ramchandra Paudel has assigned additional portfolios to three ministers. The responsibility of three ministries was given to other ministers after Kul Man Ghising, who had been taking charge of the Ministry of Energy, Water Resources and Irrigation, the Ministry of Physical Infrastructures and Transport, and the Ministry of Urban Development, resigned from the post on Wednesday.</p>,
 <p class="wp-block-paragraph">At the recommendation of Prime Minister Sushila Karki, President Paudel assigned Minister for Industry, Commerce and Supply, Anil Kumar Sinha, to look after the portfolio of the Ministry of Energy, Water Resources and Irrigation.</p>,
 <p class="wp-block-paragraph">Similarly, Minister for Forest and Environment, Madhav Prasad Chaulagain, will look after the portfolio of the Ministry of Physical Infrastructures and Transport, while Minister for Land Management, Cooperative and Poverty Alleviation, Kumar Ingnam, the portfolio of the Urban Development Minister, as well, reads a press release issued by Spokesperson at the Office of the President, Ritesh Kumar Shakya.</p>]

In [10]:
post_text=""
for p in text_section.find_all('p'):
    post_text += p.string + " "
post_text

'Kathmandu, January 9 President Ramchandra Paudel has assigned additional portfolios to three ministers. The responsibility of three ministries was given to other ministers after Kul Man Ghising, who had been taking charge of the Ministry of Energy, Water Resources and Irrigation, the Ministry of Physical Infrastructures and Transport, and the Ministry of Urban Development, resigned from the post on Wednesday. At the recommendation of Prime Minister Sushila Karki, President Paudel assigned Minister for Industry, Commerce and Supply, Anil Kumar Sinha, to look after the portfolio of the Ministry of Energy, Water Resources and Irrigation. Similarly, Minister for Forest and Environment, Madhav Prasad Chaulagain, will look after the portfolio of the Ministry of Physical Infrastructures and Transport, while Minister for Land Management, Cooperative and Poverty Alleviation, Kumar Ingnam, the portfolio of the Urban Development Minister, as well, reads a press release issued by Spokesperson at the Office of the President, Ritesh Kumar Shakya. '

### Now we have to do same for all the url and put it to the data frame

In [11]:
all_link = df['Link'].tolist()

In [ ]:
import numpy as np

actual_content = []

for i, link in enumerate(all_link):
    print(f"Scraping content for link {i+1}/{len(all_link)}")

    response = requests.get(link)
    soup = BeautifulSoup(response.text, "html.parser")

    text_section = soup.find("div", class_="post-content-wrap")

    if text_section is None:
        actual_content.append(np.nan)
        continue

    post_text = ""

    for p in text_section.find_all("p"):
        post_text += p.get_text(strip=True) + " "

    actual_content.append(post_text.strip())

In [13]:
from concurrent.futures import ThreadPoolExecutor
import numpy as np
def scrape_article(args):
    i, url = args
    print(f"Scraping {i+1}/{len(all_link)}")

    try:
        response = requests.get(url, timeout=10)

        if response.status_code != 200:
            return np.nan

        soup = BeautifulSoup(response.text, "html.parser")

        text_section = soup.find("div", class_="post-content-wrap")

        if text_section is None:
            return np.nan

        post_text = ""

        for p in text_section.find_all("p"):
            post_text += p.get_text(strip=True) + " "

        return post_text.strip()

    except Exception:
        return np.nan


with ThreadPoolExecutor(max_workers=100) as executor:
    actual_content = list(executor.map(scrape_article, enumerate(all_link)))

Scraping 1/12390
Scraping 2/12390
Scraping 3/12390
Scraping 4/12390
Scraping 5/12390
Scraping 6/12390
Scraping 7/12390
Scraping 8/12390
Scraping 9/12390
Scraping 10/12390
Scraping 11/12390
Scraping 12/12390
Scraping 13/12390
Scraping 14/12390
Scraping 15/12390
Scraping 16/12390
Scraping 17/12390
Scraping 18/12390
Scraping 19/12390
Scraping 20/12390
Scraping 21/12390
Scraping 22/12390
Scraping 23/12390
Scraping 24/12390
Scraping 25/12390
Scraping 26/12390
Scraping 27/12390
Scraping 28/12390
Scraping 29/12390
Scraping 30/12390
Scraping 31/12390
Scraping 32/12390
Scraping 33/12390
Scraping 34/12390
Scraping 35/12390
Scraping 36/12390
Scraping 37/12390
Scraping 38/12390
Scraping 39/12390
Scraping 40/12390
Scraping 41/12390
Scraping 42/12390
Scraping 43/12390
Scraping 44/12390
Scraping 45/12390
Scraping 46/12390
Scraping 47/12390
Scraping 48/12390
Scraping 49/12390
Scraping 50/12390
Scraping 51/12390
Scraping 52/12390
Scraping 53/12390
Scraping 54/12390
Scraping 55/12390
Scraping 56/12390
Scraping 57/12390
Scraping 58/12390
Scraping 59/12390
Scraping 60/12390
Scraping 61/12390
Scraping 62/12390
Scraping 63/12390
Scraping 64/12390
Scraping 65/12390
Scraping 66/12390
Scraping 67/12390
Scraping 68/12390
Scraping 69/12390
Scraping 70/12390
Scraping 71/12390
Scraping 72/12390
Scraping 73/12390
Scraping 74/12390
Scraping 75/12390
Scraping 76/12390
Scraping 77/12390
Scraping 78/12390
Scraping 79/12390
Scraping 80/12390
Scraping 81/12390
Scraping 82/12390
Scraping 83/12390
Scraping 84/12390
Scraping 85/12390
Scraping 86/12390
Scraping 87/12390
Scraping 88/12390
Scraping 89/12390
Scraping 90/12390
Scraping 91/12390
Scraping 92/12390
Scraping 93/12390
Scraping 94/12390
Scraping 95/12390
Scraping 96/12390
Scraping 97/12390
Scraping 98/12390
Scraping 99/12390
Scraping 100/12390
Scraping 101/12390
Scraping 102/12390
Scraping 103/12390
Scraping 104/12390
Scraping 105/12390Scraping 106/12390

Scraping 107/12390
Scraping 108/12390
Scraping 109/12390
Scraping 110/12390
Scraping 111/12390
Scraping 112/12390
Scraping 113/12390
Scraping 114/12390
Scraping 115/12390
Scraping 116/12390
Scraping 117/12390
Scraping 118/12390
Scraping 119/12390
Scraping 120/12390
Scraping 121/12390
Scraping 122/12390
Scraping 123/12390
Scraping 124/12390
Scraping 125/12390
Scraping 126/12390
Scraping 127/12390
Scraping 128/12390
Scraping 129/12390
Scraping 130/12390
Scraping 131/12390
Scraping 132/12390
Scraping 133/12390
Scraping 134/12390
Scraping 135/12390
Scraping 136/12390
Scraping 137/12390
Scraping 138/12390
Scraping 139/12390
Scraping 140/12390
Scraping 141/12390
Scraping 142/12390
Scraping 143/12390
Scraping 144/12390
Scraping 145/12390
Scraping 146/12390
Scraping 147/12390
Scraping 148/12390
Scraping 149/12390
Scraping 150/12390
Scraping 151/12390
Scraping 152/12390
Scraping 153/12390
Scraping 154/12390
Scraping 155/12390
Scraping 156/12390
Scraping 157/12390
Scraping 158/12390
Scraping 159/12390
Scraping 160/12390
Scraping 161/12390
Scraping 162/12390
Scraping 163/12390
Scraping 164/12390
Scraping 165/12390
Scraping 166/12390
Scraping 167/12390
Scraping 168/12390
Scraping 169/12390
Scraping 170/12390
Scraping 171/12390
Scraping 172/12390
Scraping 173/12390
Scraping 174/12390
Scraping 175/12390
Scraping 176/12390
Scraping 177/12390
Scraping 178/12390
Scraping 179/12390
Scraping 180/12390
Scraping 181/12390
Scraping 182/12390
Scraping 183/12390
Scraping 184/12390
Scraping 185/12390
Scraping 186/12390
Scraping 187/12390
Scraping 188/12390
Scraping 189/12390
Scraping 190/12390
Scraping 191/12390
Scraping 192/12390
Scraping 193/12390
Scraping 194/12390
Scraping 195/12390
Scraping 196/12390
Scraping 197/12390
Scraping 198/12390
Scraping 199/12390
Scraping 200/12390
Scraping 201/12390
Scraping 202/12390
Scraping 203/12390
Scraping 204/12390
Scraping 205/12390
Scraping 206/12390
Scraping 207/12390
Scraping 208/12390
Scraping 209/12390
Scraping 210/12390
Scraping 211/12390
Scraping 212/12390
Scraping 213/12390Scraping 214/12390
Scraping 215/12390
Scraping 216/12390

Scraping 217/12390
Scraping 218/12390
Scraping 219/12390
Scraping 220/12390
Scraping 221/12390
Scraping 222/12390
Scraping 223/12390
Scraping 224/12390
Scraping 225/12390
Scraping 226/12390
Scraping 227/12390
Scraping 228/12390
Scraping 229/12390
Scraping 230/12390
Scraping 231/12390
Scraping 232/12390
Scraping 233/12390
Scraping 234/12390
Scraping 235/12390
Scraping 236/12390
Scraping 237/12390
Scraping 238/12390
Scraping 239/12390
Scraping 240/12390
Scraping 241/12390
Scraping 242/12390
Scraping 243/12390
Scraping 244/12390
Scraping 245/12390
Scraping 246/12390
Scraping 247/12390
Scraping 248/12390
Scraping 249/12390
Scraping 250/12390
Scraping 251/12390
Scraping 252/12390
Scraping 253/12390
Scraping 254/12390
Scraping 255/12390
Scraping 256/12390
Scraping 257/12390
Scraping 258/12390
Scraping 259/12390
Scraping 260/12390
Scraping 261/12390
Scraping 262/12390
Scraping 263/12390
Scraping 264/12390
Scraping 265/12390
Scraping 266/12390
Scraping 267/12390
Scraping 268/12390
Scraping 269/12390
Scraping 270/12390
Scraping 271/12390
Scraping 272/12390
Scraping 273/12390
Scraping 274/12390
Scraping 275/12390
Scraping 276/12390
Scraping 277/12390
Scraping 278/12390
Scraping 279/12390
Scraping 280/12390
Scraping 281/12390
Scraping 282/12390
Scraping 283/12390
Scraping 284/12390
Scraping 285/12390Scraping 286/12390
Scraping 287/12390
Scraping 288/12390
Scraping 289/12390
Scraping 290/12390

Scraping 291/12390
Scraping 292/12390
Scraping 293/12390
Scraping 294/12390
Scraping 295/12390
Scraping 296/12390
Scraping 297/12390
Scraping 298/12390
Scraping 299/12390
Scraping 300/12390
Scraping 301/12390
Scraping 302/12390
Scraping 303/12390
Scraping 304/12390
Scraping 305/12390
Scraping 306/12390
Scraping 307/12390
Scraping 308/12390
Scraping 309/12390
Scraping 310/12390
Scraping 311/12390
Scraping 312/12390
Scraping 313/12390
Scraping 314/12390
Scraping 315/12390
Scraping 316/12390
Scraping 317/12390
Scraping 318/12390
Scraping 319/12390
Scraping 320/12390
Scraping 321/12390
Scraping 322/12390
Scraping 323/12390
Scraping 324/12390
Scraping 325/12390
Scraping 326/12390Scraping 327/12390
Scraping 328/12390
Scraping 329/12390
Scraping 330/12390
Scraping 331/12390
Scraping 332/12390
Scraping 333/12390
Scraping 334/12390
Scraping 335/12390
Scraping 336/12390
Scraping 337/12390
Scraping 338/12390
Scraping 339/12390
Scraping 340/12390

Scraping 341/12390
Scraping 342/12390
Scraping 343/12390
Scraping 344/12390
Scraping 345/12390
Scraping 346/12390
Scraping 347/12390
Scraping 348/12390
Scraping 349/12390
Scraping 350/12390Scraping 351/12390
Scraping 352/12390

Scraping 353/12390
Scraping 354/12390
Scraping 355/12390
Scraping 356/12390
Scraping 357/12390
Scraping 358/12390
Scraping 359/12390Scraping 360/12390

Scraping 361/12390
Scraping 362/12390
Scraping 363/12390
Scraping 364/12390
Scraping 365/12390
Scraping 366/12390
Scraping 367/12390
Scraping 368/12390
Scraping 369/12390
Scraping 370/12390
Scraping 371/12390
Scraping 372/12390
Scraping 373/12390
Scraping 374/12390
Scraping 375/12390
Scraping 376/12390
Scraping 377/12390
Scraping 378/12390
Scraping 379/12390Scraping 380/12390
Scraping 381/12390
Scraping 382/12390
Scraping 383/12390
Scraping 384/12390
Scraping 385/12390Scraping 386/12390
Scraping 387/12390

Scraping 388/12390
Scraping 389/12390
Scraping 390/12390
Scraping 391/12390Scraping 392/12390
Scraping 393/12390

Scraping 394/12390

Scraping 395/12390
Scraping 396/12390
Scraping 397/12390
Scraping 398/12390
Scraping 399/12390
Scraping 400/12390
Scraping 401/12390
Scraping 402/12390
Scraping 403/12390
Scraping 404/12390
Scraping 405/12390
Scraping 406/12390
Scraping 407/12390
Scraping 408/12390
Scraping 409/12390
Scraping 410/12390
Scraping 411/12390
Scraping 412/12390
Scraping 413/12390
Scraping 414/12390
Scraping 415/12390
Scraping 416/12390
Scraping 417/12390
Scraping 418/12390
Scraping 419/12390
Scraping 420/12390
Scraping 421/12390
Scraping 422/12390
Scraping 423/12390
Scraping 424/12390
Scraping 425/12390
Scraping 426/12390
Scraping 427/12390
Scraping 428/12390
Scraping 429/12390
Scraping 430/12390
Scraping 431/12390
Scraping 432/12390
Scraping 433/12390
Scraping 434/12390
Scraping 435/12390
Scraping 436/12390Scraping 437/12390
Scraping 438/12390

Scraping 439/12390
Scraping 440/12390
Scraping 441/12390
Scraping 442/12390
Scraping 443/12390
Scraping 444/12390
Scraping 445/12390
Scraping 446/12390
Scraping 447/12390
Scraping 448/12390Scraping 449/12390
Scraping 450/12390
Scraping 451/12390
Scraping 452/12390
Scraping 453/12390
Scraping 454/12390
Scraping 455/12390
Scraping 456/12390
Scraping 457/12390
Scraping 458/12390
Scraping 459/12390

Scraping 460/12390
Scraping 461/12390
Scraping 462/12390
Scraping 463/12390
Scraping 464/12390
Scraping 465/12390
Scraping 466/12390
Scraping 467/12390
Scraping 468/12390
Scraping 469/12390
Scraping 470/12390
Scraping 471/12390
Scraping 472/12390
Scraping 473/12390
Scraping 474/12390
Scraping 475/12390
Scraping 476/12390
Scraping 477/12390
Scraping 478/12390
Scraping 479/12390
Scraping 480/12390
Scraping 481/12390
Scraping 482/12390
Scraping 483/12390
Scraping 484/12390
Scraping 485/12390
Scraping 486/12390
Scraping 487/12390
Scraping 488/12390
Scraping 489/12390
Scraping 490/12390
Scraping 491/12390
Scraping 492/12390
Scraping 493/12390
Scraping 494/12390
Scraping 495/12390
Scraping 496/12390
Scraping 497/12390
Scraping 498/12390
Scraping 499/12390
Scraping 500/12390
Scraping 501/12390
Scraping 502/12390
Scraping 503/12390
Scraping 504/12390
Scraping 505/12390
Scraping 506/12390
Scraping 507/12390
Scraping 508/12390
Scraping 509/12390
Scraping 510/12390
Scraping 511/12390
Scraping 512/12390
Scraping 513/12390
Scraping 514/12390
Scraping 515/12390
Scraping 516/12390
Scraping 517/12390
Scraping 518/12390
Scraping 519/12390
Scraping 520/12390
Scraping 521/12390
Scraping 522/12390
Scraping 523/12390
Scraping 524/12390
Scraping 525/12390
Scraping 526/12390
Scraping 527/12390
Scraping 528/12390
Scraping 529/12390
Scraping 530/12390
Scraping 531/12390
Scraping 532/12390
Scraping 533/12390
Scraping 534/12390
Scraping 535/12390
Scraping 536/12390
Scraping 537/12390
Scraping 538/12390
Scraping 539/12390
Scraping 540/12390
Scraping 541/12390
Scraping 542/12390
Scraping 543/12390
Scraping 544/12390Scraping 545/12390

Scraping 546/12390
Scraping 547/12390
Scraping 548/12390
Scraping 549/12390
Scraping 550/12390
Scraping 551/12390
Scraping 552/12390
Scraping 553/12390
Scraping 554/12390
Scraping 555/12390
Scraping 556/12390
Scraping 557/12390
Scraping 558/12390
Scraping 559/12390
Scraping 560/12390
Scraping 561/12390
Scraping 562/12390
Scraping 563/12390
Scraping 564/12390
Scraping 565/12390
Scraping 566/12390
Scraping 567/12390
Scraping 568/12390
Scraping 569/12390
Scraping 570/12390
Scraping 571/12390
Scraping 572/12390
Scraping 573/12390
Scraping 574/12390
Scraping 575/12390
Scraping 576/12390
Scraping 577/12390
Scraping 578/12390
Scraping 579/12390
Scraping 580/12390
Scraping 581/12390Scraping 582/12390

Scraping 583/12390
Scraping 584/12390
Scraping 585/12390
Scraping 586/12390
Scraping 587/12390
Scraping 588/12390
Scraping 589/12390
Scraping 590/12390
Scraping 591/12390
Scraping 592/12390
Scraping 593/12390
Scraping 594/12390
Scraping 595/12390
Scraping 596/12390
Scraping 597/12390
Scraping 598/12390
Scraping 599/12390
Scraping 600/12390
Scraping 601/12390
Scraping 602/12390
Scraping 603/12390
Scraping 604/12390
Scraping 605/12390
Scraping 606/12390
Scraping 607/12390
Scraping 608/12390
Scraping 609/12390
Scraping 610/12390
Scraping 611/12390
Scraping 612/12390
Scraping 613/12390
Scraping 614/12390
Scraping 615/12390
Scraping 616/12390
Scraping 617/12390
Scraping 618/12390
Scraping 619/12390
Scraping 620/12390
Scraping 621/12390
Scraping 622/12390
Scraping 623/12390
Scraping 624/12390
Scraping 625/12390
Scraping 626/12390
Scraping 627/12390
Scraping 628/12390
Scraping 629/12390
Scraping 630/12390
Scraping 631/12390
Scraping 632/12390
Scraping 633/12390
Scraping 634/12390
Scraping 635/12390
Scraping 636/12390
Scraping 637/12390
Scraping 638/12390
Scraping 639/12390
Scraping 640/12390Scraping 641/12390
Scraping 642/12390

Scraping 643/12390
Scraping 644/12390
Scraping 645/12390
Scraping 646/12390
Scraping 647/12390
Scraping 648/12390
Scraping 649/12390
Scraping 650/12390
Scraping 651/12390
Scraping 652/12390
Scraping 653/12390
Scraping 654/12390
Scraping 655/12390
Scraping 656/12390
Scraping 657/12390
Scraping 658/12390
Scraping 659/12390
Scraping 660/12390
Scraping 661/12390
Scraping 662/12390
Scraping 663/12390
Scraping 664/12390
Scraping 665/12390
Scraping 666/12390
Scraping 667/12390
Scraping 668/12390
Scraping 669/12390
Scraping 670/12390
Scraping 671/12390
Scraping 672/12390
Scraping 673/12390
Scraping 674/12390Scraping 675/12390
Scraping 676/12390
Scraping 677/12390
Scraping 678/12390
Scraping 679/12390
Scraping 680/12390
Scraping 681/12390
Scraping 682/12390
Scraping 683/12390
Scraping 684/12390
Scraping 685/12390

Scraping 686/12390
Scraping 687/12390
Scraping 688/12390
Scraping 689/12390
Scraping 690/12390
Scraping 691/12390
Scraping 692/12390
Scraping 693/12390
Scraping 694/12390
Scraping 695/12390
Scraping 696/12390
Scraping 697/12390
Scraping 698/12390
Scraping 699/12390
Scraping 700/12390
Scraping 701/12390
Scraping 702/12390
Scraping 703/12390
Scraping 704/12390
Scraping 705/12390
Scraping 706/12390
Scraping 707/12390
Scraping 708/12390
Scraping 709/12390
Scraping 710/12390
Scraping 711/12390
Scraping 712/12390
Scraping 713/12390
Scraping 714/12390
Scraping 715/12390
Scraping 716/12390
Scraping 717/12390
Scraping 718/12390
Scraping 719/12390
Scraping 720/12390
Scraping 721/12390
Scraping 722/12390
Scraping 723/12390
Scraping 724/12390
Scraping 725/12390
Scraping 726/12390
Scraping 727/12390
Scraping 728/12390
Scraping 729/12390
Scraping 730/12390
Scraping 731/12390
Scraping 732/12390
Scraping 733/12390Scraping 734/12390
Scraping 735/12390
Scraping 736/12390

Scraping 737/12390
Scraping 738/12390
Scraping 739/12390
Scraping 740/12390
Scraping 741/12390
Scraping 742/12390
Scraping 743/12390
Scraping 744/12390
Scraping 745/12390
Scraping 746/12390
Scraping 747/12390
Scraping 748/12390
Scraping 749/12390
Scraping 750/12390
Scraping 751/12390
Scraping 752/12390
Scraping 753/12390
Scraping 754/12390
Scraping 755/12390
Scraping 756/12390
Scraping 757/12390
Scraping 758/12390
Scraping 759/12390
Scraping 760/12390
Scraping 761/12390
Scraping 762/12390
Scraping 763/12390
Scraping 764/12390
Scraping 765/12390
Scraping 766/12390
Scraping 767/12390
Scraping 768/12390
Scraping 769/12390
Scraping 770/12390
Scraping 771/12390
Scraping 772/12390
Scraping 773/12390
Scraping 774/12390
Scraping 775/12390
Scraping 776/12390
Scraping 777/12390
Scraping 778/12390
Scraping 779/12390
Scraping 780/12390
Scraping 781/12390
Scraping 782/12390
Scraping 783/12390
Scraping 784/12390
Scraping 785/12390
Scraping 786/12390
Scraping 787/12390
Scraping 788/12390
Scraping 789/12390
Scraping 790/12390
Scraping 791/12390
Scraping 792/12390
Scraping 793/12390
Scraping 794/12390
Scraping 795/12390
Scraping 796/12390
Scraping 797/12390
Scraping 798/12390
Scraping 799/12390
Scraping 800/12390
Scraping 801/12390
Scraping 802/12390
Scraping 803/12390
Scraping 804/12390
Scraping 805/12390
Scraping 806/12390
Scraping 807/12390
Scraping 808/12390
Scraping 809/12390
Scraping 810/12390
Scraping 811/12390Scraping 812/12390
Scraping 813/12390
Scraping 814/12390

Scraping 815/12390
Scraping 816/12390
Scraping 817/12390
Scraping 818/12390
Scraping 819/12390
Scraping 820/12390
Scraping 821/12390
Scraping 822/12390Scraping 823/12390

Scraping 824/12390
Scraping 825/12390
Scraping 826/12390
Scraping 827/12390
Scraping 828/12390
Scraping 829/12390
Scraping 830/12390
Scraping 831/12390
Scraping 832/12390
Scraping 833/12390
Scraping 834/12390
Scraping 835/12390
Scraping 836/12390
Scraping 837/12390
Scraping 838/12390
Scraping 839/12390
Scraping 840/12390
Scraping 841/12390
Scraping 842/12390
Scraping 843/12390
Scraping 844/12390
Scraping 845/12390
Scraping 846/12390
Scraping 847/12390
Scraping 848/12390
Scraping 849/12390
Scraping 850/12390
Scraping 851/12390
Scraping 852/12390
Scraping 853/12390
Scraping 854/12390
Scraping 855/12390
Scraping 856/12390
Scraping 857/12390
Scraping 858/12390
Scraping 859/12390
Scraping 860/12390
Scraping 861/12390
Scraping 862/12390
Scraping 863/12390
Scraping 864/12390
Scraping 865/12390
Scraping 866/12390
Scraping 867/12390
Scraping 868/12390
Scraping 869/12390
Scraping 870/12390
Scraping 871/12390
Scraping 872/12390
Scraping 873/12390
Scraping 874/12390
Scraping 875/12390
Scraping 876/12390
Scraping 877/12390
Scraping 878/12390
Scraping 879/12390
Scraping 880/12390
Scraping 881/12390
Scraping 882/12390
Scraping 883/12390
Scraping 884/12390
Scraping 885/12390
Scraping 886/12390
Scraping 887/12390
Scraping 888/12390
Scraping 889/12390
Scraping 890/12390
Scraping 891/12390
Scraping 892/12390
Scraping 893/12390
Scraping 894/12390
Scraping 895/12390
Scraping 896/12390
Scraping 897/12390
Scraping 898/12390
Scraping 899/12390
Scraping 900/12390
Scraping 901/12390
Scraping 902/12390
Scraping 903/12390
Scraping 904/12390
Scraping 905/12390
Scraping 906/12390
Scraping 907/12390
Scraping 908/12390
Scraping 909/12390
Scraping 910/12390
Scraping 911/12390
Scraping 912/12390
Scraping 913/12390
Scraping 914/12390
Scraping 915/12390
Scraping 916/12390
Scraping 917/12390
Scraping 918/12390
Scraping 919/12390
Scraping 920/12390
Scraping 921/12390
Scraping 922/12390
Scraping 923/12390
Scraping 924/12390
Scraping 925/12390
Scraping 926/12390
Scraping 927/12390
Scraping 928/12390
Scraping 929/12390
Scraping 930/12390
Scraping 931/12390
Scraping 932/12390
Scraping 933/12390
Scraping 934/12390
Scraping 935/12390
Scraping 936/12390
Scraping 937/12390
Scraping 938/12390
Scraping 939/12390
Scraping 940/12390
Scraping 941/12390
Scraping 942/12390
Scraping 943/12390
Scraping 944/12390
Scraping 945/12390
Scraping 946/12390
Scraping 947/12390
Scraping 948/12390
Scraping 949/12390
Scraping 950/12390
Scraping 951/12390
Scraping 952/12390
Scraping 953/12390
Scraping 954/12390
Scraping 955/12390
Scraping 956/12390
Scraping 957/12390
Scraping 958/12390
Scraping 959/12390
Scraping 960/12390
Scraping 961/12390
Scraping 962/12390Scraping 963/12390
Scraping 964/12390

Scraping 965/12390
Scraping 966/12390
Scraping 967/12390
Scraping 968/12390
Scraping 969/12390
Scraping 970/12390
Scraping 971/12390
Scraping 972/12390
Scraping 973/12390
Scraping 974/12390
Scraping 975/12390
Scraping 976/12390
Scraping 977/12390
Scraping 978/12390
Scraping 979/12390
Scraping 980/12390
Scraping 981/12390
Scraping 982/12390
Scraping 983/12390
Scraping 984/12390
Scraping 985/12390
Scraping 986/12390
Scraping 987/12390
Scraping 988/12390
Scraping 989/12390
Scraping 990/12390
Scraping 991/12390
Scraping 992/12390
Scraping 993/12390
Scraping 994/12390
Scraping 995/12390
Scraping 996/12390
Scraping 997/12390
Scraping 998/12390
Scraping 999/12390
Scraping 1000/12390
Scraping 1001/12390
Scraping 1002/12390
Scraping 1003/12390
Scraping 1004/12390
Scraping 1005/12390
Scraping 1006/12390
Scraping 1007/12390
Scraping 1008/12390
Scraping 1009/12390
Scraping 1010/12390
Scraping 1011/12390
Scraping 1012/12390
Scraping 1013/12390
Scraping 1014/12390
Scraping 1015/12390
Scraping 1016/12390
Scraping 1017/12390
Scraping 1018/12390
Scraping 1019/12390
Scraping 1020/12390
Scraping 1021/12390
Scraping 1022/12390
Scraping 1023/12390
Scraping 1024/12390
Scraping 1025/12390
Scraping 1026/12390
Scraping 1027/12390
Scraping 1028/12390
Scraping 1029/12390
Scraping 1030/12390
Scraping 1031/12390
Scraping 1032/12390
Scraping 1033/12390
Scraping 1034/12390
Scraping 1035/12390
Scraping 1036/12390
Scraping 1037/12390
Scraping 1038/12390
Scraping 1039/12390
Scraping 1040/12390
Scraping 1041/12390
Scraping 1042/12390
Scraping 1043/12390
Scraping 1044/12390
Scraping 1045/12390
Scraping 1046/12390
Scraping 1047/12390
Scraping 1048/12390
Scraping 1049/12390
Scraping 1050/12390
Scraping 1051/12390
Scraping 1052/12390
Scraping 1053/12390
Scraping 1054/12390

In [14]:
actual_content

['Kathmandu, January 9 President Ramchandra Paudel has assigned additional portfolios to three ministers. The responsibility of three ministries was given to other ministers after Kul Man Ghising, who had been taking charge of the Ministry of Energy, Water Resources and Irrigation, the Ministry of Physical Infrastructures and Transport, and the Ministry of Urban Development, resigned from the post on Wednesday. At the recommendation of Prime Minister Sushila Karki, President Paudel assigned Minister for Industry, Commerce and Supply, Anil Kumar Sinha, to look after the portfolio of the Ministry of Energy, Water Resources and Irrigation. Similarly, Minister for Forest and Environment, Madhav Prasad Chaulagain, will look after the portfolio of the Ministry of Physical Infrastructures and Transport, while Minister for Land Management, Cooperative and Poverty Alleviation, Kumar Ingnam, the portfolio of the Urban Development Minister, as well, reads a press release issued by Spokesperson at the Office of the President, Ritesh Kumar Shakya.',
 'Kathmandu, January 9 Legal hurdles have been cleared to obtain the citizenship certificate in the mother’s name. With the new move, anyone whose father’s identity is not revealed will receive the citizenship certificate in the mother’s name, following the approval of the Nepal Citizenship (Fourth Amendment) Regulations, 2082. The Council of Ministers had approved the Nepal Citizenship (Fourth Amendment) Regulations and published them in the Nepal Gazette on January 5, paving the way for the implementation of the provision stated in the Citizenship Act, 2063. Spokesperson of the Ministry of Home Affairs, Ananda Kafle, stated that all the District Administration Offices across the country have been written for the implementation of the provision mentioned in the Nepal Citizenship (Fourth Amendment) Regulations. The President, in September, had authenticated the Nepal Citizenship (Second Amendment) Bill, 2082, made to amend the Nepal Citizenship Act, 2063 BS. The amendment ensures provisions allowing anyone to acquire citizenship in the mother’s name if the identity of their father remains unknown. Regarding naturalised citizenship, it states that a child born to a Nepali female citizen in a foreign country, who resides permanently in Nepal, may be granted naturalised citizenship as prescribed, provided the child has not acquired foreign citizenship through their father. The Regulations also mentioned that a child is eligible for obtaining citizenship in the mother’s name if the father is dead or not supporting the child in acquiring citizenship, or is married to another person.',
 'Kathmandu, December 8 The Nepal Army is preparing to deploy around 80,000 personnel for the upcoming House of Representatives election scheduled for Falgun 21. Nepal Army Assistant Chief of Staff and spokesperson Rajaram Basnet said that troop deployment will be carried out in line with the Integrated Security Plan 2082, which has already been approved by the government and endorsed by the President. He said the army will be mobilised in the field one month prior to the election, as guided by the integrated security plan. The Integrated Security Plan has been approved by the government, and the National Security Council has also endorsed the army’s mobilisation. The army will operate in three phases during the election period. In the pre-election phase, its key responsibilities will include securing ballot paper printing and protecting vital infrastructure. In coordination and cooperation with Nepal Police and the Armed Police Force Nepal, the Nepal Army will also be responsible for the security of key installations such as airports and prisons. As part of the election preparations, the army will conduct integrated training and drills related to the election down to the local level, in coordination with all four security agencies and district administrations. These exercises aim to help ensure that the election is conducted in a free, fair, impartial, and fear-free environment. On polling day, the Nepal Army will remain in the third security ring at polling stations and centres, providing full security assurance to political parties, candidates, voters, and election personnel. As in previous elections, the army is preparing to establish security bases at various locations across the country. After voting concludes on Falgun 21, the army will take responsibility for transporting ballot boxes and securing vote-counting centres. Security meetings are currently being held at the provincial level to ensure the election is conducted in a safe and fear-free environment. Based on the suggestions received in these meetings, the government will further assess and analyse the situation and make additional security arrangements as needed. The Nepal Army has stated that all security forces, local administrations, and people’s representatives are ready to work in coordination and cooperation to provide election security, which it described as a primary responsibility of the state.',
 'Kathmandu, January 8 The Election Commission has introduced a new regulation concerning communications within the election code of conduct. The Commission declared on January 7 during an event here that, throughout the election campaign prohibition period, no form of discussion, interaction, assembly, convention, workshop, or seminar is permitted, and it is forbidden to solicit votes or campaign through any method, process, or medium. According to the newly established regulation, details of campaign expenditures via online media must also be accounted for in election expenses. Political parties, candidates, and party-affiliated organisations are required to conduct their campaigns through online media and report such expenses in the election expense documentation. Furthermore, the new regulation emphasises the internalisation of the complete press freedom guaranteed by the Constitution along with its self-regulation. The definition of social media has been broadened to encompass specific social media platforms, while the utilisation of artificial intelligence (AI) to contravene the code of conduct in evolving times has also been addressed. Provisions have been established to permit promotional materials to be published in any newspaper as part of newspaper promotions, and arrangements have been made to facilitate election campaigns through online media utilising roadblocks, content blocks, homepage banners, detailed page banners, and box advertisements (within the news).',
 'Kathmandu, January 8 Minister for Energy, Water Resources and Irrigation Kulman Ghising has resigned from his post. Minister Ghising reached the Prime Minister’s official residence, Baluwatar, and submitted his resignation before Prime Minister Sushila Karki on January 7. Ghising, who had also been in charge of the Ministry of Infrastructure and Transportation and Urban Development, was appointed as the minister on September 15, 2025. On this occasion, Prime Minister Karki expressed gratitude for providing able leadership to the three crucial ministries over the past three and a half months, the PM secretariat shared. “You have performed as a minister of the incumbent government under very adverse conditions, contributing greatly to the country”, Prime Minister Karki said. “You worked untiringly around the clock. You reached various parts of the country and remained equally active during times of disaster. You personally went to disaster-affected areas and worked there, and also took strict measures against irregularities in the development and construction projects. The country will remember your work, and the people will evaluate it.” Minister Ghising expressed gratitude to the Prime Minister for providing the opportunity to work during the interim period. Ghising resigned after questions were raised over his affiliation with a political party, preparing to contest the upcoming March 5 elections. It may be noted that an understanding has been reached between the Ujjyalo Party Nepal, which Ghising oversees, and the Rastriya Swatantra Party for a potential merger. According to the understanding, he is set to become the vice president of the Rastriya Swatantra Party.',
 'Damauli, January 5 Tanahun district has a total of 254,397 voters for the election to the House of Representatives (HoR) scheduled for March 5. According to the District Election Office, Tanahun, women voters are more compared to the men voters in the district. The Office shared that the number of men voters is 123,491 and the women voters are 130,906. District Election Officer Bikas Lamsal said that Vyas Municipality has the highest number of voters and Devghat Rural Municipality has the lowest number in the district. He said there are 136,118 voters in constituency no. 1 and 118,279 voters in constituency no. 2 in Tanahun district. Lamsal stated that 309 voting centres have been managed in the district. The Election Commission had collected the voters’ names from September 26 to Novemebr 21, 2025 by targeting the upcoming election to the House of Representatives scheduled for March 5.',
 'Baitadi, January 4 The district committees of the Land Problem Resolution Commission have reactivated their efforts. Ramesh Pandey, the chairperson of the District Committee, announced that activities at the district level resumed following the Supreme Court’s annulment of the government’s decision to disband the commission. During a district committee meeting attended by District Coordination Committee Chief Khagendra Singh Dhami and Chief District Officer Punya Bikram Paudel, it was resolved to dispatch letters to municipalities requesting information on landless Dalits, landless squatter communities, and irregular settlers by February 8. In line with this resolution, communication was established with all 10 local levels in the district, as reported by Binod Prasad Bhatt, Secretary of the Committee and Head of the Survey Office. The correspondence sent to the municipalities outlined tasks, including the entry of applications gathered from all wards into the Commission’s computer system, the formation of Ward and Local Level Facilitation Committees, the posting of notices regarding claims opposition as per established procedures, conducting necessary investigations and verifications of applications. Similarly, publishing lists of applications that have not been verified as requested, identifying land that can be allocated according to regulations for landless Dalits and squatters, obtaining decisions from the executive, and supplying the district committee with information and verified decisions from both ward and executive levels concerning landless Dalits, landless squatters, and unorganised settlers are in progress.',
 'Kathmandu, December 31 Out of the 64 political parties that submitted their closed lists for the proportional representation system for the upcoming House of Representatives elections, 22 parties have filed candidacies for all 110 seats. In the closed list submitted to the Election Commission on December 28 and 29, only 22 parties have nominated 110 candidates for the proportional representation system. Commission spokesperson Narayan Prasad Bhattarai said that out of a total of 64 parties that submitted their lists, 58 parties have filed candidacies for 58 election symbols. The political parties fielding candidates in all (110) seats are Nepali Congress, CPN (UML), Nepal Communist Party (NCP), Rastriya Swatantra Party, Nepal Workers and Peasants Party, Rastriya Janamorcha, Mongol National Organization, Democratic Socialist Party, CPN (ML), Labor Culture Party, Federal Democratic National Forum, Nepal Sadbhavana Party, Janamat Party, Miteri Party Nepal, Nepal Communist Party (United). Similarly, Nepali Janata Dal, National Democratic Party, Nepal Communist Party (Maoist), Progressive Democratic Party and some parties have submitted closed lists for 110 seats by organising joint elections and combining their lists. In the upcoming election of members of the House of Representatives to be held on March 5, parties have filed candidacies based on the percentage of inclusive groups as per the 2021 census. In the meantime, as some parties have agreed on unity and cooperation, the process of submitting closed lists continued until late at night. Out of 93 political parties that applied to the Commission to file candidacies under this system, only 64 parties have filed candidacies.',
 'Kathmandu, December 31 Minister for Physical Infrastructure and Transport Kulman Ghising has warned that contractors responsible for delays in road construction projects will face penalties, and that the government may terminate contracts if needed. Speaking at the 23rd anniversary of Road Board Nepal on December 30, the minister said the government would no longer tolerate contractors who fail to complete road projects within the stipulated deadlines. “This is not a matter of choice for the government, but a compulsion.” The minister also added that while the demand for road improvements is high, limited budget allocations have become a major obstacle to intervening on such projects on time. Secretary at the Ministry of Physical Infrastructure and Transport, Keshab Kumar Sharma, said that development should not be measured merely by construction. He stressed the need for building usable and quality roads, adding that the timely restoration of damaged roadways is an urgent priority. Road Board Nepal Executive Director Ganesh Bahadur KC said that delays in maintaining damaged roads increase costs by three to four times. Likewise, Director General of the Department of Roads, Dr Bijay Jaishi, described road infrastructure as the backbone of development and called for guaranteeing the budget to ensure the timely restoration of damaged roadways.',
 'Kathmandu, December 31 Minister for Foreign Affairs, Bala Nanda Sharma, left for Dhaka, Bangladesh, last night to attend the state funeral of former Prime Minister and Chairperson of the Bangladesh Nationalist Party, Begum Khaleda Zia. Sharma is paying his previous respects on behalf of the government and the people of Nepal. The Foreign Minister’s visit reflects Nepal’s deep respect for the late leader’s contributions to strengthening Nepal–Bangladesh relations during her three tenures as Prime Minister, said the Foreign Ministry in a statement, adding that Minister Sharma would be accompanied by senior officials of the Foreign Ministry. The Minister is scheduled to return home on January 1, 2026.',

In [15]:
df["Content"] = actual_content
df.head()

,Posts,URL,Category,Link,Content
0,Three ministers get additional portfolios,{'url': 'https://english.onlinekhabar.com/thre...,Politics,https://english.onlinekhabar.com/three-ministe...,"Kathmandu, January 9 President Ramchandra Paud..."
1,Legal ways paved to provide citizenship in mot...,{'url': 'https://english.onlinekhabar.com/lega...,Politics,https://english.onlinekhabar.com/legal-ways-pa...,"Kathmandu, January 9 Legal hurdles have been c..."
2,"Upcoming HoR election to see deployment of 80,...",{'url': 'https://english.onlinekhabar.com/upco...,Politics,https://english.onlinekhabar.com/upcoming-hor-...,"Kathmandu, December 8 The Nepal Army is prepar..."
3,New regulation incorporated into the Election ...,{'url': 'https://english.onlinekhabar.com/new-...,Politics,https://english.onlinekhabar.com/new-regulatio...,"Kathmandu, January 8 The Election Commission h..."
4,Energy Minister Ghising resigns,{'url': 'https://english.onlinekhabar.com/ener...,Politics,https://english.onlinekhabar.com/energy-minist...,"Kathmandu, January 8 Minister for Energy, Wate..."

### Keeping only the Revalant Columns and Dropping Other Columns

In [23]:
df.drop(columns=["URL", "Link", "Posts"], inplace=True)
df.head()

   Category                                            Content
0  Politics  Kathmandu, January 9 President Ramchandra Paud...
1  Politics  Kathmandu, January 9 Legal hurdles have been c...
2  Politics  Kathmandu, December 8 The Nepal Army is prepar...
3  Politics  Kathmandu, January 8 The Election Commission h...
4  Politics  Kathmandu, January 8 Minister for Energy, Wate...

In [24]:
df.to_excel("OnlineKhabar_New.xlsx", index=False)